#!/bin/bash

arg=$1

if [[ $arg == "up" ]]; then
    pactl set-sink-volume 0 +5%
elif [[ $arg == "down" ]]; then
    pactl set-sink-volume 0 -5%
else
    exit
fi

volume=$(pactl list sinks | egrep Volume | head -n1 | awk '{print $5}')
dunstify "$volume" --appname="Volume" -r 999
